/* This is a very basic example header file */

#ifndef libnyx_h
#define libnyx_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdbool.h>

typedef enum NyxProcessRole {
  StandAlone,
  Parent,
  Child,
} NyxProcessRole;

typedef enum NyxReturnValue {
  Normal,
  Crash,
  Asan,
  Timeout,
  InvalidWriteToPayload,
  Error,
  IoError,
  Abort,
} NyxReturnValue;

typedef struct NyxProcess NyxProcess;

void *nyx_config_load(const char *sharedir);

void nyx_config_debug(void *config);

void nyx_config_print(void *config);

void nyx_config_set_workdir_path(void *config, const char *workdir);

void nyx_config_set_input_buffer_size(void *config, uint32_t input_buffer_size);

void nyx_config_set_input_buffer_write_protection(void *config, bool input_buffer_write_protection);

void nyx_config_set_hprintf_fd(void *config, int32_t hprintf_fd);

void nyx_config_set_process_role(void *config, enum NyxProcessRole role);

void nyx_config_set_reuse_snapshot_path(void *config, const char *reuse_snapshot_path);

struct NyxProcess *nyx_new(void *config, uint32_t worker_id);

uint8_t *nyx_get_aux_buffer(struct NyxProcess *nyx_process);

uint8_t *nyx_get_input_buffer(struct NyxProcess *nyx_process);

uint8_t *nyx_get_bitmap_buffer(struct NyxProcess *nyx_process);

size_t nyx_get_bitmap_buffer_size(struct NyxProcess *nyx_process);

void nyx_shutdown(struct NyxProcess *nyx_process);

void nyx_option_set_reload_mode(struct NyxProcess *nyx_process, bool enable);

void nyx_option_set_timeout(struct NyxProcess *nyx_process,
                            uint8_t timeout_sec,
                            uint32_t timeout_usec);

void nyx_option_apply(struct NyxProcess *nyx_process);

enum NyxReturnValue nyx_exec(struct NyxProcess *nyx_process);

void nyx_set_afl_input(struct NyxProcess *nyx_process, uint8_t *buffer, uint32_t size);

void nyx_print_aux_buffer(struct NyxProcess *nyx_process);

uint32_t nyx_get_aux_string(struct NyxProcess *nyx_process, uint8_t *buffer, uint32_t size);

void nyx_set_hprintf_fd(struct NyxProcess *nyx_process, int32_t fd);

bool nyx_remove_work_dir(const char *workdir);

#endif /* libnyx_h */
