# Automatically generated by configure - do not modify
SRC_PATH=/home/wx/Shaw/myAFLpp/nyx_mode/QEMU-Nyx/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
