# Automatically generated by configure - do not modify
TARGET_NAME=x86_64
CONFIG_SOFTMMU=y
QEMU=$(BUILD_DIR)/x86_64-softmmu/qemu-system-x86_64
CROSS_CC_GUEST_CFLAGS=-m64
CROSS_CC_GUEST_STATIC=y
CROSS_CC_GUEST=cc
